version: '2'
services:
  db_volume:
    extends:
      file: docker-compose.base.yml
      service: db_volume
  db:
    extends:
      file: docker-compose.base.yml
      service: db
    volumes_from:
      - db_volume
    restart: always
  smtp:
    image: namshi/smtp
    restart: always
  rabbitmq:
    extends:
      file: docker-compose.base.yml
      service: rabbitmq
    restart: always
  celery:
    extends:
      file: docker-compose.base.yml
      service: celery
    env_file: .env
    depends_on:
      - rabbitmq
      - db
    environment:
      - "DJANGO_SETTINGS_MODULE=instances.production"
    restart: always
    volumes_from:
      - web
    # This part is a problem: web depends on celery to run,
    # but celery depends on web volumes (uploads, medias/, etc).
    # For now we avoid circular dependencies by avoiding web <- celery
    # TODO(laurent): use volumes to avoid this situation
  flower:
    extends:
      file: docker-compose.base.yml
      service: flower
    depends_on:
      - celery
      - rabbitmq
    restart: always
  web:
    extends:
      file: docker-compose.base.yml
      service: web
    env_file: .env
    restart: always
    environment:
      - "DJANGO_SETTINGS_MODULE=instances.production"
    depends_on:
      - db
      - smtp
    ports:
      - "8742:8000"
  web_scripts:
    extends:
      file: docker-compose.base.yml
      service: web
    env_file: .env
    environment:
      - "DJANGO_SETTINGS_MODULE=instances.production"
    depends_on:
      - db
      - smtp
      - celery
    volumes:
      - .:/app
  media:
    image: lsenta/noconf-nginx
    depends_on:
      - web
    ports:
      - 8843:80
    environment:
      - "STATIC_FOLDER=/app/media"
    volumes_from:
      - web
  static:
    image: lsenta/noconf-nginx
    depends_on:
      - web
    ports:
      - "8842:80"
    environment:
      - "STATIC_FOLDER=/app/static"
    volumes_from:
      - web
