version: '2'
services:
  db:
    extends:
      file: docker-compose.base.yml
      service: db
    restart: always
  smtp:
    image: namshi/smtp
    restart: always
  rabbitmq:
    extends:
      file: docker-compose.base.yml
      service: rabbitmq
    restart: always
  celery:
    extends:
      file: docker-compose.base.yml
      service: celery
    depends_on:
      - rabbitmq
    environment:
      - "DJANGO_SETTINGS_MODULE=instances.production"
    restart: always
  flower:
    extends:
      file: docker-compose.base.yml
      service: flower
    depends_on:
      - celery
      - rabbitmq
    restart: always
  web:
    extends:
      file: docker-compose.base.yml
      service: web
    env_file: .env
    restart: always
    environment:
      - "DJANGO_SETTINGS_MODULE=instances.production"
    depends_on:
      - db
      - smtp
      - celery
    ports:
      - "8742:8000"
  media:
    image: lsenta/noconf-nginx
    depends_on:
      - web
    ports:
      - 8843:80
    environment:
      - "STATIC_FOLDER=/app/media"
    volumes_from:
      - web
  static:
    image: lsenta/noconf-nginx
    depends_on:
      - web
    ports:
      - "8842:80"
    environment:
      - "STATIC_FOLDER=/app/static"
    volumes_from:
      - web
