version: '2'
services:
  db:
    extends:
      file: docker-compose.base.yml
      service: db
  rabbitmq:
    extends:
      file: docker-compose.base.yml
      service: rabbitmq
  celery:
    extends:
      file: docker-compose.base.yml
      service: celery
    depends_on:
      - rabbitmq
    environment:
      - "DJANGO_SETTINGS_MODULE=instances.local_docker"
    volumes:
      - .:/app
      - ./static:/app/static
  flower:
    extends:
      file: docker-compose.base.yml
      service: flower
    depends_on:
      - celery
      - rabbitmq
    ports:
      - "15555:5555"
  web:
    extends:
      file: docker-compose.base.yml
      service: web
    command: /usr/local/bin/gunicorn chalab.wsgi:application -w 2 -b :8000 --reload
    environment:
      - "DJANGO_SETTINGS_MODULE=instances.local_docker"
    volumes:
      - .:/app
      - ./static:/app/static
    depends_on:
      - db
      - celery
    ports:
      - "8000:8000"
