version: '2'
services:
  db_volume:
    extends:
      file: docker-compose.base.yml
      service: db_volume
  db:
    extends:
      file: docker-compose.base.yml
      service: db
    volumes_from:
      - db_volume
  rabbitmq:
    extends:
      file: docker-compose.base.yml
      service: rabbitmq
  celery:
    extends:
      file: docker-compose.base.yml
      service: celery
    depends_on:
      - rabbitmq
      - db
    environment:
      - "DJANGO_SETTINGS_MODULE=instances.local_docker"
    volumes:
      - .:/app
    command: celery -A chalab.chacelery worker --loglevel=debug
  flower:
    extends:
      file: docker-compose.base.yml
      service: flower
    depends_on:
      - celery
      - rabbitmq
  web:
    extends:
      file: docker-compose.base.yml
      service: web
    command: /usr/local/bin/gunicorn chalab.wsgi:application -w 2 -b :8000 --reload
    environment:
      - "DJANGO_SETTINGS_MODULE=instances.local_docker"
    volumes:
      - .:/app
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - db
      - celery
