version: '2'
services:
  db:
    extends:
      file: docker-compose.base.yml
      service: db
  web:
    extends:
      file: docker-compose.base.yml
      service: web
    command: /usr/local/bin/gunicorn chalab.wsgi:application -w 2 -b :8000 --reload
    environment:
      - "DJANGO_SETTINGS_MODULE=instances.local_docker"
    volumes:
      - .:/app
      - ./static:/app/static
    depends_on:
      - db
    ports:
      - "8000:8000"
